version: "3"
services:
  spark-master:
    image: spark-master:latest
    ports:
      - "4040:4040"
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./jdbc:/opt/spark-jdbc
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    networks:
      - spark_cluster_default
  spark-worker:
    image: spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./jdbc:/opt/spark-jdbc
    networks:
      - spark_cluster_default

networks:
  spark_cluster_default:
    external: true
